version: "3"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - mongo_network
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    expose:
      - "8081"
    networks:
      - mongo_network
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    depends_on:
      - mongo

  api:
    image: meli-test-image
    ports:
      - 8000:8000
    expose:
      - "8000"
    networks:
      - mongo_network
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MAX_QUEUE_SIZE=1000
      - PYTHONBUFFERED=1
      - EMPTYING_TIME=30
      - ENVIRONMENT=PROD
      - LOG_LEVEL=DEBUG
      - WORKERS_PER_CORE=2
      - HOST=0.0.0.0
      - PORT=8000
    command: [
        "gunicorn",
        "app.app:app",
        "app/gunicorn_conf.py",
        # "--workers",
        # "4",
        "--worker-class",
        "uvicorn.workers.UvicornWorker",
        "--threads",
        "2",
      ]
    restart: unless-stopped
    env_file:
      - .env

networks:
  mongo_network:
    driver: bridge
