version: "3"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - mongo_network
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DBUSERNAME
      MONGO_INITDB_ROOT_PASSWORD: $DBPASSWORD

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    networks:
      - mongo_network
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_SERVER: $MONGO_HOST
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DBUSERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DBPASSWORD
    depends_on:
      - mongo
  api:
    image: meli-test-image
    ports:
      - 8000:8000
    expose:
      - "8000"
    networks:
      - mongo_network
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=$MONGO_PORT
      - MAX_QUEUE_SIZE=$MAX_QUEUE_SIZE
      - PYTHONBUFFERED=1
      - EMPTYING_TIME=$EMPTYING_TIME
      - ENVIRONMENT=$ENVIRONMENT
      - LOG_LEVEL=DEBUG
    command: ["gunicorn", "-c", "app/gunicorn_conf.py", "app.app:app"]
    restart: unless-stopped
    env_file:
      - .env

networks:
  mongo_network:
    driver: bridge
