[tool.poetry]
name = "meli-test"
version = "0.1.0"
description = "Software Development Engineer Test for Mercado Libre"
authors = ["Leonardo HG <leonardohg.ipn@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
numpy = "^1.22.3"
scipy = "^1.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
